version: '2.4'
x-openvpn-network: &openvpn-network
  depends_on:
  - 'openvpn'
  network_mode: 'service:openvpn'
  restart: 'unless-stopped'
services:
  openvpn:
    image: 'jpbaking/cpto-openvpn:latest'
    build:
      context: 'openvpn'
      dockerfile: 'openvpn.Dockerfile'
    cap_add:
    - 'NET_ADMIN'
    devices:
    - '/dev/net/tun'
    volumes:
    - './.openvpn:/.openvpn:ro'
    restart: 'unless-stopped'
  tinyproxy:
    image: 'jpbaking/cpto-tinyproxy:latest'
    build:
      context: 'tinyproxy'
      dockerfile: 'tinyproxy.Dockerfile'
    <<: *openvpn-network
  srelay:
    image: 'jpbaking/cpto-srelay:latest'
    build:
      context: 'srelay'
      dockerfile: 'srelay.Dockerfile'
    <<: *openvpn-network
  haproxy:
    image: 'jpbaking/cpto-haproxy:latest'
    build:
      context: 'haproxy'
      dockerfile: 'haproxy.Dockerfile'
    ports:
    - '0.0.0.0:23128:3128'
    - '0.0.0.0:21080:1080'
    depends_on:
    - 'openvpn'
    - 'tinyproxy'
    - 'srelay'
    restart: 'unless-stopped'
