version: '2.4'
x-openvpn-network: &openvpn-network
  depends_on:
  - 'openvpn'
  network_mode: 'service:openvpn'
  restart: 'unless-stopped'
services:
  openvpn:
    image: 'jpbaking/cpto-openvpn:latest'
    build:
      context: 'cpto-openvpn'
      dockerfile: 'openvpn.Dockerfile'
    command: "${OPENVPN_CMD_ARGS}"
    cap_add:
    - 'NET_ADMIN'
    devices:
    - '/dev/net/tun'
    volumes:
    - '${OPENVPN_CONFIG_DIR}:/.openvpn:ro'
    restart: 'unless-stopped'
  tinyproxy:
    image: 'jpbaking/cpto-tinyproxy:latest'
    build:
      context: 'cpto-tinyproxy'
      dockerfile: 'tinyproxy.Dockerfile'
    <<: *openvpn-network
  srelay:
    image: 'jpbaking/cpto-srelay:latest'
    build:
      context: 'cpto-srelay'
      dockerfile: 'srelay.Dockerfile'
    <<: *openvpn-network
  haproxy:
    image: 'jpbaking/cpto-haproxy:latest'
    build:
      context: 'cpto-haproxy'
      dockerfile: 'haproxy.Dockerfile'
    ports:
    - '0.0.0.0:${HTTP_PROXY_PORT}:3128'
    - '0.0.0.0:${SOCKS_PROXY_PORT}:1080'
    depends_on:
    - 'openvpn'
    - 'tinyproxy'
    - 'srelay'
    restart: 'unless-stopped'
