apiVersion: v1
kind: ConfigMap
metadata:
  name: cpto-config
  namespace: cpto
data:
  tinyproxy.conf: |
    User tinyproxy
    Group tinyproxy
    Port 3128
    Timeout 600
    DefaultErrorFile "/usr/share/tinyproxy/default.html"
    LogLevel Connect
    MaxClients 1024
    MinSpareServers 32
    MaxSpareServers 1024
    StartServers 64
    MaxRequestsPerChild 0
    ViaProxyName "tinyproxy"
  srelay.conf: |
    0.0.0.0    any
